# 定义常用标点符号的中文与英文对应关系
PunctuationMarks = {
    "等于": "=",
    "全等": "==",
    "不等": "!=",
    "大于": ">",
    "小于": "<",
    "减": "-",
    "加": "+",
    "乘": "*",
    "除": "/",
    "取模": "%",
    "（": "(",
    "）": ")",
    "：": ":",
    "“": '"',
    "”": '"',
    "，": ",",
    "；": ";",
    "，": ",",
    "‘": "'",
    "’": "'",
    "【": "[",
    "】": "]",
    "？": "?",
    "！": "!",
}

# # 定义常用关键字的中文与英文对应关系
# Keywords = {
#     "导入": "import",
#     "特定导入": "from",
#     "定义": "def",
#     "如果": "if",
#     "否则": "else",
#     "和": "and",
#     "或": "or",
#     "结束": "break",
#     "迭代": "for",
#     "循环": "while",
#     "整型": "int",
#     "浮点数": "float",
#     "复数": "complex",
#     "字符串": "str",
#     "元组": "tuple",
#     "列表": "list",
#     "范围": "range",
#     "字典": "dict",
#     "集合": "set",
#     "不可变集合": "frozenset",
#     "布尔类型": "bool",
#     "空类型": "None",
#     "格式化字符串": "f",
#     "打印": "print",
#     "输入框": "input",
#     "退出": "exit",
#     "返回": "return",
#     "类": "class",
#     "对象": "object",
#     "异常": "except",
#     "捕获": "try",
#     "除数为零": "ZeroDivisionError",
#     "文件不存在": "FileNotFoundError",
#     "索引错误": "IndexError",
#     "键错误": "KeyError",
#     "类型错误": "TypeError",
#     "值错误": "ValueError",
#     "断言": "assert",
#     "打开": "open",
#     "读取": "read",
#     "写入": "write",
#     "关闭": "close",
#     "别名": "as",
#     "真": "True",
#     "假": "False",
#     "继续": "continue",
#     "执行": "exec",
#     "全局": "global",
#     "非本地": "nonlocal",
#     "装饰器": "decorator",
#     "删除": "del",
#     "长度": "len",
#     "最大值": "max",
#     "最小值": "min",
#     "求和": "sum",
#     "枚举": "enumerate",
#     "排序": "sorted",
#     "转换为列表": "list",
#     "转换为元组": "tuple",
#     "转换为集合": "set",
#     "转换为字典": "dict",
#     "范围生成器": "range",
#     "全局变量": "globals",
#     "局部变量": "locals",
#     "终止程序": "exit",
#     "帮助": "help",
# }

# 定义常用内置模块的中文与英文对应关系
BuiltinModules = {
    # 模块
    "随机数": "random",
    "时间": "time",
    "数学": "math",
    "文件操作": "os",
    "JSON处理": "json",
    "命令行参数解析": "argparse",
    "正则表达式": "re",
    "日期时间处理": "datetime",
    "数据压缩": "zlib",
    "网络通信": "socket",
    "并发编程": "concurrent.futures",
    "日志记录": "logging",
    "HTTP客户端": "urllib.request",
    "HTTP服务器": "http.server",
    "HTML解析": "html.parser",
    "XML解析": "xml.etree.ElementTree",
    "邮件处理": "email",
    "CSV文件处理": "csv",
    "数据序列化": "pickle",
    "图形界面": "tkinter",
    "图像对话框": "filedialog",
    "数据库连接": "sqlite3",
    "加密解密": "hashlib",
    "科学计算": "numpy",
    "数据可视化": "matplotlib",
    "机器学习": "scikit-learn",
    "深度学习": "tensorflow",
    # 使用方法
    "随机整数": "random.randint",
    "随机浮点数": "random.uniform",
    "获取当前时间": "time.time",
    "休眠": "time.sleep",
    "三角函数": "math.sin",
    "平方根": "math.sqrt",
    "指数运算": "math.exp",
    "对数运算": "math.log",
    "创建目录": "os.mkdir",
    "文件写入": "open",
    "JSON解析": "json.loads",
    "JSON序列化": "json.dumps",
    "读取环境变量": "os.getenv",
    "编译正则表达式": "re.compile",
    "格式化日期": "datetime.datetime.strftime",
    "解压数据": "zlib.decompress",
    "建立TCP连接": "socket.create_connection",
    "执行系统命令": "subprocess.run",
    "启动HTTP服务器": "http.server.HTTPServer",
    "解析HTML内容": "html.parser.HTMLParser",
    "解析XML文档": "xml.etree.ElementTree.parse",
    "发送电子邮件": "email.message.EmailMessage",
    "读取CSV文件": "csv.reader",
    "写入CSV文件": "csv.writer",
    "对象序列化": "pickle.dumps",
    "创建主窗口": "tkinter.Tk",
    "创建新线程": "threading.Thread",
    "启动新进程": "multiprocessing.Process",
    "连接SQLite数据库": "sqlite3.connect",
    "计算哈希值": "hashlib.sha256",
    "科学计算基础库": "numpy",
    "绘制数据可视化图表": "matplotlib.pyplot",
    "机器学习模型训练": "sklearn.linear_model.LinearRegression.fit",
    "深度学习模型构建": "tensorflow.keras.Sequential",
    # tkinter模块及方法
    "创建按钮": "tkinter.Button",
    "创建标签": "tkinter.Label",
    "创建文本框": "tkinter.Entry",
    "创建列表框": "tkinter.Listbox",
    "创建滚动条": "tkinter.Scrollbar",
    "创建菜单": "tkinter.Menu",
    "创建对话框": "tkinter.messagebox",
}


Keywords1 = {
    "导入": "import",
    "特定导入": "from",
    "如果": "if",
    "否则": "else",
    "结束": "break",
    "迭代": "for",
    "循环": "while",
    "定义": "def",
    "返回": "return",
    "类": "class",
    "异常": "except",
    "捕获": "try",
    "断言": "assert",
    "删除": "del",
    "全局": "global",
    "非本地": "nonlocal",
    "别名": "as",
}
Keywords2 = {
    "读取": "read",
    "写入": "write",
    "关闭": "close",
    "装饰器": "decorator",
    "继续": "continue",
}
Keywords3 = {
    "和": "and",
    "或": "or",
    "空类型": "None",
    "真": "True",
    "假": "False",
}
Keywords4 = {
    "整型": "int",
    "浮点数": "float",
    "复数": "complex",
    "字符串": "str",
    "元组": "tuple",
    "列表": "list",
    "字典": "dict",
    "集合": "set",
    "不可变集合": "frozenset",
    "布尔类型": "bool",
    "对象": "object",
    "除数为零": "ZeroDivisionError",
    "文件不存在": "FileNotFoundError",
    "索引错误": "IndexError",
    "键错误": "KeyError",
    "类型错误": "TypeError",
    "值错误": "ValueError",
    "转换为列表": "list",
    "转换为元组": "tuple",
    "转换为集合": "set",
    "转换为字典": "dict",
}
Keywords5 = {
    "范围": "range",
    "打印": "print",
    "输入框": "input",
    "退出": "exit",
    "打开": "open",
    "范围生成器": "range",
    "全局变量": "globals",
    "局部变量": "locals",
    "终止程序": "exit",
    "帮助": "help",
    "长度": "len",
    "最大值": "max",
    "最小值": "min",
    "求和": "sum",
    "枚举": "enumerate",
    "排序": "sorted",
    "执行": "exec",
}
